### ISSUE TITLE
View style not taking hold on page load

### ISSUE THREAD

**Issue by jgrody** [jshanson7/react-native-swipeable#1]
Hi,

Been trying to get a working version of this up and running. Been the easiest swipe library to use so far but I'm having a strange issue. 

I'm following along Example #3 from the docs:

```
render() {
    const {leftActionActivated, toggle} = this.state;

    return (
      <Swipeable
        onLeftActionActivate={() => this.setState({leftActionActivated: true})}
        onLeftActionDeactivate={() => this.setState({leftActionActivated: false})}
        onLeftActionComplete={() => this.setState({toggle: !toggle})}
        leftActionActivationDistance={200}
        leftContent={(
          <View style={[styles.leftSwipeItem, {backgroundColor: leftActionActivated ? 'lightgoldenrodyellow' : 'steelblue'}]}>
            {leftActionActivated ?
              <Text>release!</Text> :
              <Text>keep pulling!</Text>}
          </View>
        )}
      >
        <View style={[styles.listItem, {backgroundColor: toggle ? 'thistle' : 'darkseagreen'}]}>
          <Text>Example 3</Text>
        </View>
      </Swipeable>
    );
  }
```

On page load, the `onLeftActionActivate` function actually runs, I get console.log output, however the `<View/>` background color does not change and the `release!` text never gets displayed. It only works after I perform some action in my app and then go back to the list and try again.

![out](https://cloud.githubusercontent.com/assets/1022253/21740058/2bfedbee-d47b-11e6-879c-50a38a1d7f51.gif)

Please let me know if you have any idea whats going on. Thanks!

**Comment by jgrody** [comment]
I solved my issue by moving my swipeable rows to their own component

**Comment by jshanson7** [comment]
@jgrody that's very strange -- if you figure out what was going on, please let me know!

**Comment by pencilcheck** [comment]
I also have this issue. I can't figure out how to make the setState actually re-render the views

**Comment by pencilcheck** [comment]
Oh, you have to follow the example precisely, you need to specifically have activation state to be in the component separate instead of with the parent component that manages the listview

https://github.com/jshanson7/react-native-swipeable/blob/master/example/swipeable-example.js
