### ISSUE TITLE
Is manual open possible?

### ISSUE THREAD

**Issue by alburdette619** [jshanson7/react-native-swipeable#11]
Maybe via a button press?

**Comment by jshanson7** [comment]
Unfortunately that hasn't been built out -- open to pull requests though.  I think the best solution might be to make an optional stateless version of the component where everything is set via props.

**Comment by alburdette619** [comment]
I have a PR open: https://github.com/dancormier/react-native-swipeout/pull/161

**Comment by rtman** [comment]
@jshanson7 @alburdette619 

I just noticed that this pr was opened for a different component, this isn't for react-native-swipeable? Why is it referenced here? Can we get a similar function for react-native-swipeable?

**Comment by rtman** [comment]
@alburdette619 @jshanson7 

Can you guys comment on this?

**Comment by alburdette619** [comment]
Wow major egg on my face there. Very sorry.
