### ISSUE TITLE
Cells with Left/Right margin show swipe content in the margin

### ISSUE THREAD

**Issue by kellenlask** [jshanson7/react-native-swipeable#22]
The library probably wasn't intended to be used in this way, but I figured you'd want to know about it.

**Comment by kellenlask** [comment]
Oh, adding the cells to the list was incidental, I forgot about iOS's desire to render things outside a view's bounds. The real fix was adding:  `removeClippedSubviews={true}` to the cell

**Comment by junedomingo** [comment]
solution above is working, in addition, if you have marginHorintal in your view, just add overflow: 'hidden' in style.
