### ISSUE TITLE
Buttons not visible on Android

### ISSUE THREAD

**Issue by nicinabox** [jshanson7/react-native-swipeable#4]
![screen shot 2017-01-18 at 13 40 38](https://cloud.githubusercontent.com/assets/246280/22080089/d98e93c4-dd83-11e6-811b-1ae72b9b755d.png)

Everything appears to render correctly in the right position, but it seems like something clipping and preventing the buttons from being visible. I'm using a ListView and Swipeable is the root of `renderRow`. 

I dug through the 0.3.2 diff in hopes of finding a clue, but I got nothing. Any ideas?

**Comment by jshanson7** [comment]
Hi @nicinabox, sorry for the delay I've been traveling.  Can you post some code so I can get a better idea of what's happening?  My guess is that the button content needs some styling to fill up it's container -- have you given it `flex: 1`?

**Comment by nicinabox** [comment]
No worries!

Here's my `RowAction` passed to which is passed in an array to `rightButtons`:

```javascript
import React, { PropTypes } from 'react'
import { StyleSheet, TouchableHighlight, View, Text } from 'react-native'

export default function RowAction (props) {
  return (
    <TouchableHighlight style={{flex:1}} onPress={props.onPress}>
      <View style={[styles.button, props.style]}>
        <Text style={[styles.buttonText, props.textStyle]}>
          {props.children}
        </Text>
      </View>
    </TouchableHighlight>
  )
}

var styles = StyleSheet.create({
  button: {
    paddingHorizontal: 20,
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#aaa',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  buttonText: {
    color: 'white'
  }
})

RowAction.propTypes = {
  children: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
  onPress: PropTypes.func,
}

RowAction.defaultProps = {
  onPress: () => {}
}
```

**Comment by jshanson7** [comment]
Added your `RowAction` to the examples - 74d4536cd841b82c0d695f1545b07c2b320e6b01.  I'll try debugging it on Android when I get back home to my iMac in a few days.  Works fine on iOS though:
<img width="487" alt="screen shot 2017-01-27 at 3 28 47 pm" src="https://cloud.githubusercontent.com/assets/2469458/22362341/50c0dc54-e4a5-11e6-9f56-c3af4a6c9c2c.png">

**Comment by nicinabox** [comment]
Yeah, it's working flawlessly on iOS for me too. They seem to be clipped or something on Android.

**Comment by nicinabox** [comment]
Checked out your branch to run the example and it works fine on Android. This must be related to `ListView`.

**Comment by nicinabox** [comment]
Okay, this is weird. I've made no changes to my work, but I checked out my branch again and it seems to work just fine. All I can think of is that maybe I had done a `run-android` and that changed something.

Also confirmed that your example runs on Android with `ListView`. 

As unsatisfactory as that fix is: good news it's all fine.

**Comment by jshanson7** [comment]
Haha awesome let me know if you see the issue again!
