### ISSUE TITLE
Close Swipeable Card on Right Button Press

### ISSUE THREAD

**Issue by michaelfriedman** [jshanson7/react-native-swipeable#48]
How do I get the swipeable card to close or return to it's original position after a right button press?

**Comment by InsidiousClu** [comment]
@michaelfriedman seems like you should use something like this
```
someMethod = () => {
  const rightButtons = [
            <TouchableHighlight onPress={() => this.swipeable.recenter()}><Text>Button 1</Text></TouchableHighlight>,
            <TouchableHighlight><Text>Button 2</Text></TouchableHighlight>
        ];

        return (
            <Swipeable onRef={ref => this.swipeable = ref} key={index} leftContent={null} rightButtons={rightButtons}>
                <Text>My swipeable content</Text>
            </Swipeable>
        );
}
```

**Comment by michaelfriedman** [comment]
Like this... but I just set the `onRef={ref => this.swipeable = ref}` on the Swipeable and set swipeable = null in component state. Then on button press `this.swipeable.recenter()`

**Comment by jaycee425** [comment]
doesnt seems to work, it gives me a `undefined is not object evaluating this.swipable.recenter`

I work on
react-native-cli: 2.0.1
react-native: 0.48.4
npm: 5.3.0
node: v8.2.1

**Comment by michaelfriedman** [comment]
You misspelled ‘swipeable’ not ‘swipable.’

-- 
Michael Friedman

**Comment by michaelfriedman** [comment]
Show your code.

**Comment by Ramesh-Chathuranga** [comment]
```Try this if some one have issue when click on button
```
<Swipeable>  onRef={ref => this.swipeable = ref}  
leftButtons={leftbutton}
</Swipeable>
   ```
        leftbutton = ()=>{
```
<TouchableOpacity onPress={()=>{
                             if (this.swipeable){
                                  this.swipeable.recenter();
                             }
                `}>click</TouchableOpacity>`
}       
```
```    
```
```
