### ISSUE TITLE
onPress action

### ISSUE THREAD

**Issue by Unforgiven-wanda** [jshanson7/react-native-swipeable#5]
Hello,
I would like to be able to capture the simple `onPress` or `onLongPress` on this component. Wrapping it up inside a touchable breaks everything.

Is it possible?
Thank you.

**Comment by jshanson7** [comment]
Hi @Unforgiven-wanda, can you try putting the `Touchable` inside of the `Swipeable` as the top-level child?   I've been doing that in my apps.  Let me know if you have any issues.

**Comment by Unforgiven-wanda** [comment]
Hello again,
unfortunately it didn't work.
Here is my code, I am using Swipeable in addition to the NativeBase list item:

```javascript
<Swipeable style={style.listItem} leftContent={leftContent} rightButtons={rightButtons}>
	<TouchableNativeFeedback onPress={() => alert('test')} background={TouchableNativeFeedback.SelectableBackground()}>
	    <ListItem>
	        <Thumbnail source={require('./14767942682683.png')} />
	        <Text>Kumar Pratik</Text>
	        <Text note>Doing what you like will always keep you happy . .</Text>
	    </ListItem>
	</TouchableNativeFeedback>
</Swipeable>
```
This way the swiping works but the alert is not triggered when clicking.
When putting the `Touchable` on top, the swiping does not work, and strangely enough, clicking does not work either, only when trying to swap the elment does the press event get triggered. I have no idea why.

**Comment by jshanson7** [comment]
Can you try putting `ListItem` on the top level above the Touchable?  You'll probably need to replace it with a `View` since I think touchables only allow one child.

**Comment by Unforgiven-wanda** [comment]
Indeed it worked. Although it ruined the entire styling, I'll look into how to fix that later.
Thank you.

**Comment by Geek-Jokey** [comment]
> Indeed it worked. Although it ruined the entire styling, I'll look into how to fix that later.
> Thank you.

hello, How did you fixed it?  Could you show me your final structure？Thanks.

**Comment by HZSamir** [comment]
@Geek-Jokey Apologies I honestly do not even remember using this lib, let alone opening this issue.
