### ISSUE TITLE
How to swipe programmatically?

### ISSUE THREAD

**Issue by grigy** [jshanson7/react-native-swipeable#51]

**Comment by grigy** [comment]
@richeterre yes, something like this worked for me:

    rightActionReleaseAnimationFn={Animated.timing}
    rightActionReleaseAnimationConfig={{
        toValue: {x: -maxWidth, y: 0},
        duration: 250,
        easing: Easing.elastic(0.5)
    }}

**Comment by richeterre** [comment]
@grigy: Ah, you mean for animating the `Swipeable` as a consequence of the user swiping, such as in a "hide to swipe card" scenario. While that's super useful too, what I meant was more something like showing the user a demo of how to swipe when the component first mounts, without any required user interaction. But I figured it out by simply wrapping the `Swipeable` in an `Animated.View` and animating that one using RN's own animation API.

**Comment by freshedgarT** [comment]
@grigy I tried your approach, but couldn't get it to work.
Could you elaborate on how you were able to swipe programmatically?
Just to clarify what I mean by swipe programmatically: I want to press a button and `Swipeable` opens `rightButtons` just as if I had swiped.

**Comment by grigy** [comment]
Hi, I understand that the title may be confusing and this may not be what you want. But it doesn't start swiping programmatically, which is still triggered by user. It just continues swiping by using animation. Sorry for confusion.

**Comment by thalelinh** [comment]
> @grigy: Ah, you mean for animating the `Swipeable` as a consequence of the user swiping, such as in a "hide to swipe card" scenario. While that's super useful too, what I meant was more something like showing the user a demo of how to swipe when the component first mounts, without any required user interaction. But I figured it out by simply wrapping the `Swipeable` in an `Animated.View` and animating that one using RN's own animation API.

Could you paste a code sample with this, please? ;-;

**Comment by sergey-kozel** [comment]
See #78

**Comment by jeronnex2** [comment]
is this possible? I want to put a button in my swipeable and when it is clicked it will automatically swipe left and see other 2 buttons.
