### ISSUE TITLE
Disabling swipe

### ISSUE THREAD

**Issue by Unforgiven-wanda** [jshanson7/react-native-swipeable#6]
Hello again,
I'd like to disable a swipeable element once it has been activated, say, by a left pull. How could I achieve that?
I've skimmed through the extensive props list but haven't come across anything that might help.

Thank you.

**Comment by jshanson7** [comment]
This can be achieved by if `leftContent`, `rightContent`, `leftButtons`, `rightButtons` are all either not provided, or set to `null`.

**Comment by Unforgiven-wanda** [comment]
Thank you. Closing then. :)
