### ISSUE TITLE
Close siblings when one is activated

### ISSUE THREAD

**Issue by dsc-ian** [jshanson7/react-native-swipeable#67]
Is there a method to close the siblings of swipeable under flatlist when one is being activated? 

Thanks

**Comment by AndyCrisan** [comment]
Try this
onRef={ref => this.swipeable = ref}
 rightActionActivationDistance={20}
                                           rightButtonWidth={GLOBALS.WIDTH}
                                           onRightButtonsOpenRelease={
                                               (event, gestureState, swipeable) => {
                                                   if (this.state.currentlyOpenSwipeable && this.state.currentlyOpenSwipeable !== swipeable) {
                                                       this.state.currentlyOpenSwipeable.recenter();
                                                   }
                                                   this.setState({
                                                       currentlyOpenSwipeable: swipeable
                                                   });
                                               }
                                           }
                                           onRightButtonsCloseRelease={
                                               () => this.setState({
                                                   currentlyOpenSwipeable: null
                                               })
                                           }>

**Comment by ledbetterljoshua** [comment]
@AndyCrisan it would really help to see an actual implementation example. It is not entirely clear how this would be implemented within a FlatList.
