### ISSUE TITLE
Not Working with ReactNative 0.57.6

### ISSUE THREAD

**Issue by maurobender** [jshanson7/react-native-swipeable#80]
In React Native 0.57.6 there is a change that makes conditional rendering throw an `Invariant Violation Text strings must be rendered within a <Text> component` error if the condition is not a boolean value (See: [[0.56.0] Text strings must be rendered within a <Text> component](https://github.com/facebook/react-native/issues/20084)).

I'm having this error being thrown using `Swipeable` component with empty buttons and I located the error in this piece of code:

```javascript
return (
      <View onLayout={this._handleLayout} style={[styles.container, style]} {...this._panResponder.panHandlers} {...props}>
        {canSwipeRight && (
          <Animated.View style={[{transform, marginLeft: -width, width}, leftContainerStyle]}>
            {leftContent || this._renderButtons(leftButtons, true)}
          </Animated.View>
        )}
        <Animated.View style={[{transform}, styles.content, contentContainerStyle]}>{children}</Animated.View>
        {canSwipeLeft && (
          <Animated.View style={[{transform, marginRight: -width, width}, rightContainerStyle]}>
            {rightContent || this._renderButtons(rightButtons, false)}
          </Animated.View>
        )}
      </View>
    );
  }
```

In particular the `canSwipeRight` and `canSwipeLeft` conditions.

I have resolve the error by making the private methods `_canSwipeLeft` and `_canSwipeRight` return always a boolean like this:

```javascript
 _canSwipeRight() {
  return !!this.props.leftContent || this._hasLeftButtons();
}

_canSwipeLeft() {
  return !!this.props.rightContent || this._hasRightButtons();
}

_hasLeftButtons() {
  const {leftButtons, leftContent} = this.props;

  return !leftContent && !!leftButtons && leftButtons.length > 0;
}

_hasRightButtons() {
  const {rightButtons, rightContent} = this.props;

  return !rightContent && !!rightButtons && rightButtons.length > 0;
}
```

I'll create a fork to solve this but it will be good to do a good test of the library with this RN version.

**Comment by sbichenko** [comment]
Yep, the package does not work with the latest React Native version.
