### ISSUE TITLE
how to close?

### ISSUE THREAD

**Issue by lanten** [jshanson7/react-native-swipeable#9]
I want to close row when I click the button

**Comment by Elf2707** [comment]
As I understand use onRef prop and get ref to Swipeable:
<Swipeable onRef={ref => this.$swipe = ref} ... >
.....
</Swipeable>

and after that somewhere in action handler:
if (this.$swipe) {
  this.$swipe.recenter();
}

it works for me, but I'm not sure if it's hack or it's a good way)

**Comment by lanten** [comment]
@Elf2707 
thank you very much ! 
is works so deft

**Comment by fvonhoven** [comment]
Don't forget to add the `key` prop to your rendered rows 👍

**Comment by jshanson7** [comment]
@lanten let me know if you have any other issues.  @Elf2707 yeah it's kinda hacky, open to good ways to approach this without forcing people to use some custom `ScrollView`.

**Comment by carlo-fontanos** [comment]
The solution doesn't seem to work for me, here's my code:

`
export default class Images extends Component {
    constructor(props) {
		super(props);	
        this.swipe = null;        
        this.state = {
            gallery: api
        }
	}
    
    render() {
        return (
            <View>    
                <List
                    dataArray={this.state.gallery}
                    renderRow={(database) =>
                        <Swipeable onRef={(swipe) => this.swipe = swipe}  rightButtons={[
                            <TouchableOpacity onPress={() => {
                                this.deleteImage(database.id);
                            }}>
                                <Text>Delete</Text>
                            </TouchableOpacity>,
                            <TouchableOpacity onPress={() => {
                                this._setFeaturedImage(database.id);
                            }}>
                                <Text style={{color: 'white', paddingLeft: 23}}>Set Featured</Text>
                            </TouchableOpacity>,
                        ]}>
                            <ListItem>
                                <Thumbnail square source={{ uri: database.url }} />
                                <Body>
                                    <Text note>Attachment ID: { database.id }</Text>
                                </Body>
                            </ListItem>
                        </Swipeable>
                    }>
                </List>
            </View>
        );
    }
    
    _setFeaturedImage(){
        this.swipe.reset();
    }
    
}
`
Help please?

**Comment by dnszero** [comment]
@carlo-fontanos You need to call `this.swipe.recenter()` in your handler, not `reset()`
